### ISSUE TITLE
TypeScript type declaration file

### ISSUE THREAD

**Issue by geopic** [chegele/Logger#1]
If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

**Comment by chegele** [comment]
> If you want I can write a TypeScript type declaration file for this package so that TS developers can utilise the type-checking feature of the language as they use this package. Let me know if you are interested.

I was not expecting anyone to use this module. It was released to be used as a dependency for some of my other projects. I think I would like to take the opportunity to learn by making a declaration file myself, but I do appreciate the offer. 

I'll close this issue once it is done.

**Comment by geopic** [comment]
That's absolutely fine if you'd like to write it yourself. I'll close the issue and move on. :smiley:
